name: Build and Deploy

on:
  push:
    branches: 
    - develop

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.18.1'
          registry-url: "https://npm.greensock.com/"
          scope: "@gsap"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: add gatsby-cli@3.5.0
      - name: Install Gatsby CLI
        uses: borales/actions-yarn@v4
        with:
          cmd: install 
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Verify build
        run: ls -la public